### ISSUE TITLE
Doesn't work with media queries

### ISSUE THREAD

**Issue by mriehema** [anton-rudeshko/CSSReorder#11]
this code will not be sorted

``` css
    @media only screen and (max-width: 650px) {
      .teaserNav .morelinks {
        margin: 0;
        padding: 0;
        height: 0;
        overflow: hidden;
        width: 100%
      }
    }   
```
