### ISSUE TITLE
Reorder properties inside an @at-root directive (Sass)

### ISSUE THREAD

**Issue by lvl-em** [anton-rudeshko/CSSReorder#17]
I'm using CSSReorder in my `.scss` files, but it doesn't work when the Sass code is wrapped by an `@at-root` directive.

Eg:

``` scss
.parent {
     @at-root {
         .child-1 {
             text-align: center;
             max-width: 960px;
             position: relative;
             margin:0 auto;
         }
     }

    @at-root .child-2 {
        text-align: center;
        max-width: 960px;
        position: relative;
        margin:0 auto;
    }
 }
```
